### ISSUE TITLE
Duplicate module name: ViewportMetrics

### ISSUE THREAD

**Issue by n-amabile-brightplan** [uhlryk/react-dynamic-number#18]
```
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /node_modules/react-dynamic-number/node_modules/react/lib/ViewportMetrics.js collides with /node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
Error: @providesModule naming collision:
  Duplicate module name: ViewportMetrics
  Paths: /node_modules/react-dynamic-number/node_modules/react/lib/ViewportMetrics.js collides with /node_modules/react/lib/ViewportMetrics.js

This error is caused by a @providesModule declaration with the same name accross two different files.
    at HasteMap._updateHasteMap (/node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:162:15)
    at /node_modules/react-native/node_modules/node-haste/lib/DependencyGraph/HasteMap.js:127:25
```

**Comment by uhlryk** [comment]
Hi
Thanks for this bug report.
I have suspicious what is wrong, but to be sure I want to reproduce it.
Therefore please write steps to reproduce it. How did you get this message.

Please write your npm version too.

**Comment by n-amabile-brightplan** [comment]
@uhlryk I have a react and react-native project, both are using the same actions and reducers, but the UI is completely different. However, when I try to run the native project (`react-native run-ios`), I see that error on the console. I'm not using this package on any react-native view, it is just being used on the web files. 
Thanks in advance
